DROP VIEW IF EXISTS LEAGUE_SALARIES;
#FD VIEW of SALARIES of every Player and Coach in League
CREATE VIEW LEAGUE_SALARIES  AS SELECT TEAM_NAME,FULL_NAME,POSITION,SALARY,AGE
FROM (SELECT TEAM_NAME, FULL_NAME,POSITION,P.SALARY, AGE
FROM (SELECT TEAM_ID,FULL_NAME,POSITION,SALARY, AGE
FROM PLAYER
UNION ALL
SELECT TEAM_ID,FULL_NAME,POSITION, SALARY AS SALARY,AGE
FROM COACH
ORDER BY SALARY) as P JOIN TEAM ON P.TEAM_ID = TEAM.LEAGUE_ID) AS S;

#QUERY FOR ABOVE VIEW
SELECT *
FROM LEAGUE_SALARIES;

#FD CREATE VIEW OF SEASON GAME RESULTS
CREATE VIEW LEAGUE_RESULTS AS SELECT TEAM_NAME, W, L
FROM (SELECT A.T_NAME AS TEAM_NAME, SUM(WIN) AS W, SUM(LOSS) AS L
FROM (SELECT  HOMETEAM_NAME AS T_NAME , SUM(HOMETEAM_RESULT = 'Win') AS WIN, SUM(HOMETEAM_RESULT = 'Lose') AS LOSS
FROM GAME_STATS 
GROUP BY HOMETEAM_NAME
UNION ALL
SELECT AWAYTEAM_NAME, SUM(AWAYTEAM_RESULT = 'Win') AS WIN, SUM(AWAYTEAM_RESULT = 'Lose') AS LOSS
FROM GAME_STATS
GROUP BY AWAYTEAM_NAME) AS A
GROUP BY T_NAME
ORDER BY T_NAME) AS B;

#QUERY FOR ABOVE VIEW
SELECT *
FROM LEAGUE_RESULTS;